"""
Static REF table data — seeded once at init.
"""

REF_DATA: dict[str, list[dict]] = {
    "REF_ACCOUNT_STATUS": [
        {
            "status_code": "ACTIVE",
            "status_description": "Active account in good standing",
            "is_active": 1,
            "weight_pct": 70.0,
        },
        {
            "status_code": "DELINQUENT",
            "status_description": "Past due — missed one or more payments",
            "is_active": 1,
            "weight_pct": 12.0,
        },
        {
            "status_code": "SUSPENDED",
            "status_description": "Temporarily suspended",
            "is_active": 0,
            "weight_pct": 5.0,
        },
        {
            "status_code": "CHARGEOFF",
            "status_description": "Written off as bad debt",
            "is_active": 0,
            "weight_pct": 8.0,
        },
        {
            "status_code": "CLOSED",
            "status_description": "Account closed",
            "is_active": 0,
            "weight_pct": 5.0,
        },
    ],
    "REF_CARD_STATUS": [
        {
            "status_code": "ACTIVE",
            "status_description": "Card active and usable",
            "is_usable": 1,
            "weight_pct": 75.0,
        },
        {
            "status_code": "BLOCKED",
            "status_description": "Blocked — fraud investigation",
            "is_usable": 0,
            "weight_pct": 5.0,
        },
        {
            "status_code": "EXPIRED",
            "status_description": "Past expiry date",
            "is_usable": 0,
            "weight_pct": 8.0,
        },
        {
            "status_code": "CANCELLED",
            "status_description": "Permanently cancelled",
            "is_usable": 0,
            "weight_pct": 7.0,
        },
        {
            "status_code": "LOST",
            "status_description": "Reported lost",
            "is_usable": 0,
            "weight_pct": 3.0,
        },
        {
            "status_code": "STOLEN",
            "status_description": "Reported stolen",
            "is_usable": 0,
            "weight_pct": 2.0,
        },
    ],
    "REF_CARD_BRAND": [
        {"brand_code": "Visa", "brand_name": "Visa", "bin_prefix": "4", "weight_pct": 45.0},
        {
            "brand_code": "Mastercard",
            "brand_name": "Mastercard",
            "bin_prefix": "5",
            "weight_pct": 40.0,
        },
        {
            "brand_code": "Amex",
            "brand_name": "American Express",
            "bin_prefix": "37",
            "weight_pct": 10.0,
        },
        {"brand_code": "Interac", "brand_name": "Interac", "bin_prefix": "63", "weight_pct": 5.0},
    ],
    "REF_TRANSACTION_TYPE": [
        {
            "type_code": "PURCHASE",
            "type_description": "Standard purchase",
            "is_debit": 1,
            "weight_pct": 60.0,
        },
        {
            "type_code": "CASH_ADVANCE",
            "type_description": "Cash advance",
            "is_debit": 1,
            "weight_pct": 5.0,
        },
        {
            "type_code": "PAYMENT",
            "type_description": "Payment received",
            "is_debit": 0,
            "weight_pct": 20.0,
        },
        {
            "type_code": "REFUND",
            "type_description": "Merchant refund",
            "is_debit": 0,
            "weight_pct": 8.0,
        },
        {"type_code": "FEE", "type_description": "Fee charge", "is_debit": 1, "weight_pct": 3.0},
        {
            "type_code": "INTEREST",
            "type_description": "Interest charge",
            "is_debit": 1,
            "weight_pct": 3.0,
        },
        {
            "type_code": "REVERSAL",
            "type_description": "Transaction reversal",
            "is_debit": 0,
            "weight_pct": 1.0,
        },
    ],
    "REF_DISPUTE_TYPE": [
        {"type_code": "FRAUD", "type_description": "Unauthorized transaction", "weight_pct": 40.0},
        {
            "type_code": "NOT_RECEIVED",
            "type_description": "Goods/services not received",
            "weight_pct": 20.0,
        },
        {"type_code": "DUPLICATE", "type_description": "Duplicate charge", "weight_pct": 15.0},
        {
            "type_code": "WRONG_AMOUNT",
            "type_description": "Incorrect amount charged",
            "weight_pct": 15.0,
        },
        {
            "type_code": "QUALITY",
            "type_description": "Goods/services not as described",
            "weight_pct": 7.0,
        },
        {
            "type_code": "SUBSCRIPTION",
            "type_description": "Cancelled subscription rebilled",
            "weight_pct": 3.0,
        },
    ],
    "REF_CHARGEBACK_STAGE": [
        {
            "stage_code": "FIRST_CHARGEBACK",
            "stage_description": "Initial chargeback filed",
            "stage_order": 1,
        },
        {
            "stage_code": "REPRESENTMENT",
            "stage_description": "Merchant representment",
            "stage_order": 2,
        },
        {
            "stage_code": "PRE_ARBITRATION",
            "stage_description": "Pre-arbitration filing",
            "stage_order": 3,
        },
        {"stage_code": "ARBITRATION", "stage_description": "Network arbitration", "stage_order": 4},
    ],
    "REF_FRAUD_ALERT_TYPE": [
        {
            "alert_type_code": "VELOCITY",
            "alert_type_description": "Unusual transaction velocity",
            "detection_system": "rule_engine",
            "weight_pct": 30.0,
        },
        {
            "alert_type_code": "GEO_ANOMALY",
            "alert_type_description": "Geographic anomaly",
            "detection_system": "RTD",
            "weight_pct": 20.0,
        },
        {
            "alert_type_code": "CARD_TESTING",
            "alert_type_description": "Suspected card testing",
            "detection_system": "rule_engine",
            "weight_pct": 15.0,
        },
        {
            "alert_type_code": "HIGH_RISK_MCC",
            "alert_type_description": "High-risk merchant category",
            "detection_system": "rule_engine",
            "weight_pct": 10.0,
        },
        {
            "alert_type_code": "LARGE_TXN",
            "alert_type_description": "Unusually large transaction",
            "detection_system": "CardGuard",
            "weight_pct": 15.0,
        },
        {
            "alert_type_code": "3DS_FAIL",
            "alert_type_description": "3DS authentication failure",
            "detection_system": "3DS",
            "weight_pct": 5.0,
        },
        {
            "alert_type_code": "SCORE_DROP",
            "alert_type_description": "Significant risk score drop",
            "detection_system": "scoring",
            "weight_pct": 5.0,
        },
    ],
    "REF_AUTH_RESPONSE": [
        {
            "response_code": "00",
            "response_description": "Approved",
            "is_approved": 1,
            "weight_pct": 80.0,
        },
        {
            "response_code": "05",
            "response_description": "Do not honour",
            "is_approved": 0,
            "weight_pct": 5.0,
        },
        {
            "response_code": "14",
            "response_description": "Invalid card number",
            "is_approved": 0,
            "weight_pct": 2.0,
        },
        {
            "response_code": "51",
            "response_description": "Insufficient funds",
            "is_approved": 0,
            "weight_pct": 6.0,
        },
        {
            "response_code": "54",
            "response_description": "Expired card",
            "is_approved": 0,
            "weight_pct": 3.0,
        },
        {
            "response_code": "57",
            "response_description": "Transaction not permitted",
            "is_approved": 0,
            "weight_pct": 2.0,
        },
        {
            "response_code": "61",
            "response_description": "Exceeds withdrawal limit",
            "is_approved": 0,
            "weight_pct": 1.0,
        },
        {
            "response_code": "78",
            "response_description": "No account",
            "is_approved": 0,
            "weight_pct": 1.0,
        },
    ],
    "REF_POS_ENTRY_MODE": [
        {
            "entry_mode_code": "chip",
            "entry_mode_description": "EMV chip",
            "is_card_present": 1,
            "weight_pct": 45.0,
        },
        {
            "entry_mode_code": "contactless",
            "entry_mode_description": "Contactless/NFC",
            "is_card_present": 1,
            "weight_pct": 30.0,
        },
        {
            "entry_mode_code": "swipe",
            "entry_mode_description": "Magnetic stripe",
            "is_card_present": 1,
            "weight_pct": 5.0,
        },
        {
            "entry_mode_code": "ecommerce",
            "entry_mode_description": "E-commerce / CNP",
            "is_card_present": 0,
            "weight_pct": 15.0,
        },
        {
            "entry_mode_code": "manual",
            "entry_mode_description": "Manual entry",
            "is_card_present": 0,
            "weight_pct": 3.0,
        },
        {
            "entry_mode_code": "atm",
            "entry_mode_description": "ATM",
            "is_card_present": 1,
            "weight_pct": 2.0,
        },
    ],
    "REF_CHANNEL": [
        {"channel_code": "in_store", "channel_description": "Physical store", "weight_pct": 45.0},
        {"channel_code": "online", "channel_description": "Online / web", "weight_pct": 35.0},
        {"channel_code": "mobile", "channel_description": "Mobile app", "weight_pct": 15.0},
        {"channel_code": "telephone", "channel_description": "Telephone order", "weight_pct": 3.0},
        {"channel_code": "atm", "channel_description": "ATM", "weight_pct": 2.0},
    ],
    "REF_DELINQUENCY_BUCKET": [
        {
            "bucket_code": "CURRENT",
            "bucket_description": "Current — no missed payments",
            "min_days": 0,
            "max_days": 0,
            "bucket_order": 0,
        },
        {
            "bucket_code": "B1",
            "bucket_description": "1–30 days past due",
            "min_days": 1,
            "max_days": 30,
            "bucket_order": 1,
        },
        {
            "bucket_code": "B2",
            "bucket_description": "31–60 days past due",
            "min_days": 31,
            "max_days": 60,
            "bucket_order": 2,
        },
        {
            "bucket_code": "B3",
            "bucket_description": "61–90 days past due",
            "min_days": 61,
            "max_days": 90,
            "bucket_order": 3,
        },
        {
            "bucket_code": "B4",
            "bucket_description": "91–120 days past due",
            "min_days": 91,
            "max_days": 120,
            "bucket_order": 4,
        },
        {
            "bucket_code": "B5",
            "bucket_description": "120+ days past due",
            "min_days": 121,
            "max_days": 999,
            "bucket_order": 5,
        },
    ],
    "REF_CURRENCY": [
        {
            "currency_code": "CAD",
            "currency_name": "Canadian Dollar",
            "symbol": "CA$",
            "decimal_places": 2,
        },
        {"currency_code": "USD", "currency_name": "US Dollar", "symbol": "$", "decimal_places": 2},
        {"currency_code": "EUR", "currency_name": "Euro", "symbol": "€", "decimal_places": 2},
        {
            "currency_code": "GBP",
            "currency_name": "British Pound",
            "symbol": "£",
            "decimal_places": 2,
        },
    ],
    "REF_COUNTRY": [
        {"country_code": "CA", "country_name": "Canada", "region": "NA"},
        {"country_code": "US", "country_name": "United States", "region": "NA"},
        {"country_code": "GB", "country_name": "United Kingdom", "region": "EU"},
    ],
    "REF_STATUS_REASON": [
        {
            "reason_code": "PAYMENT_RECEIVED",
            "reason_description": "Payment received in full",
            "applies_to_status": "ACTIVE",
        },
        {
            "reason_code": "CREDIT_APPROVED",
            "reason_description": "Credit application approved",
            "applies_to_status": "ACTIVE",
        },
        {
            "reason_code": "MISSED_PAYMENT",
            "reason_description": "Minimum payment not received",
            "applies_to_status": "DELINQUENT",
        },
        {
            "reason_code": "FRAUD_CONFIRMED",
            "reason_description": "Fraud confirmed on account",
            "applies_to_status": "SUSPENDED",
        },
        {
            "reason_code": "OVERLIMIT",
            "reason_description": "Account over credit limit",
            "applies_to_status": "SUSPENDED",
        },
        {
            "reason_code": "CHARGEOFF_BAD_DEBT",
            "reason_description": "Written off — bad debt",
            "applies_to_status": "CHARGEOFF",
        },
        {
            "reason_code": "CUSTOMER_REQUEST",
            "reason_description": "Closed at customer request",
            "applies_to_status": "CLOSED",
        },
        {
            "reason_code": "BANK_DECISION",
            "reason_description": "Closed by bank decision",
            "applies_to_status": "CLOSED",
        },
    ],
    "REF_SENSITIVITY_LEVEL": [
        {
            "sensitivity_code": "PII",
            "sensitivity_description": "Personally Identifiable Information",
            "generation_rule": "faker_approved",
            "applicable_regulations": "PIPEDA, GDPR",
        },
        {
            "sensitivity_code": "PCI",
            "sensitivity_description": "Payment Card Industry Data",
            "generation_rule": "luhn_valid",
            "applicable_regulations": "PCI-DSS",
        },
        {
            "sensitivity_code": "PHI",
            "sensitivity_description": "Protected Health Information",
            "generation_rule": "faker_approved",
            "applicable_regulations": "PHIPA",
        },
        {
            "sensitivity_code": "NONE",
            "sensitivity_description": "No sensitivity classification",
            "generation_rule": "any",
            "applicable_regulations": "",
        },
    ],
}
